# Generated by Django 5.1.3 on 2025-09-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['inicio'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='campana',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
        migrations.AlterModelOptions(
            name='causa',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Causas'},
        ),
        migrations.AlterModelOptions(
            name='habilidad',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='organizacion',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AlterModelOptions(
            name='participacion',
            options={'ordering': ['-postulada_en'], 'verbose_name': 'Participación', 'verbose_name_plural': 'Participaciones'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['ciudad', 'nombre'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name_plural': 'Usuarios'},
        ),
    ]
